//! Toasty models and migrations for píxiū.
//!
//! Migrations live in `toasty/` next to this crate's `Cargo.toml`. They are
//! generated by the `pixiu-migrate` binary (see its docs) and embedded into
//! the server, which applies them on startup.

mod models;

use std::path::Path;

pub use models::*;
pub use toasty::{self, Db};

static MIGRATIONS: toasty::migration::MigrationSet = toasty::embed_migrations!();

#[derive(Debug, thiserror::Error)]
pub enum OpenError {
    #[error("failed to connect to the database at {path}: {source}")]
    Connect { path: String, source: toasty::Error },
    #[error("failed to configure the database: {0}")]
    Configure(toasty::Error),
    #[error("failed to apply database migrations: {0}")]
    Migrate(toasty::Error),
}

/// Connects to `url` without touching the schema.
///
/// # Errors
///
/// Fails when the URL is invalid or the database cannot be opened.
pub async fn connect(url: &str) -> toasty::Result<Db> {
    Db::builder()
        .models(toasty::models!(crate::*))
        .connect(url)
        .await
}

/// Opens (creating if needed) the SQLite database at `path` and brings its
/// schema up to date.
///
/// # Errors
///
/// Fails when the file cannot be opened or a migration fails to apply.
pub async fn open(path: &Path) -> Result<Db, OpenError> {
    let url = format!("sqlite:{}", path.display());
    let db = connect(&url).await.map_err(|source| OpenError::Connect {
        path: path.display().to_string(),
        source,
    })?;

    // WAL lets the Subsonic API keep reading while downloads write. The mode
    // is persisted in the database file, so setting it once suffices.
    toasty::sql::query("PRAGMA journal_mode = WAL")
        .exec(&mut db.clone())
        .await
        .map_err(OpenError::Configure)?;

    migrate(&db).await?;
    Ok(db)
}

/// Applies any pending embedded migrations.
///
/// # Errors
///
/// Fails when a migration cannot be applied; later migrations are skipped.
pub async fn migrate(db: &Db) -> Result<(), OpenError> {
    let report = MIGRATIONS.apply(db).await.map_err(OpenError::Migrate)?;
    if report.applied() > 0 {
        tracing::info!(
            applied = report.applied(),
            skipped = report.skipped(),
            "applied database migrations"
        );
    }
    Ok(())
}

/// The current time as stored in timestamp columns.
#[must_use]
pub fn now() -> jiff::Timestamp {
    jiff::Timestamp::now()
}
